apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "retail-edge-pass"
            - name: POSTGRES_DB
              value: "retail_db"
          resources:
            limits:
              cpu: "500m"     # Max 0.5 core
              memory: "512Mi" # Max 512MB RAM
            requests:
              cpu: "100m"     # Guaranteed 0.1 core
              memory: "128Mi" # Guaranteed 128MB RAM