apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-edge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-edge-app 
  template:
    metadata:
      labels:
        app: retail-edge-app
    spec:
      # Use the secret we created with the ACCESS_TOKEN
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv postgres-svc 5432; do echo waiting for postgres; sleep 2; done;"]
      imagePullSecrets:
        - name: google-registry-key 
      containers:
        - name: retail-edge-app
          image: europe-west3-docker.pkg.dev/retail-backbone-gcp/retail-edge-repo/retail-edge-service:latest
          imagePullPolicy: Always
          env:
            - name: DB_DSN
              value: "postgres://postgres:retail-edge-pass@postgres-svc:5432/retail_db?sslmode=disable"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: data-volume
          # This mounts the specific file into the directory
              mountPath: /app/data/inventory.json 
              subPath: inventory.json
      volumes:
        - name: data-volume
          configMap:
            name: inventory-data