Vagrant.configure("2") do |config|
  # Use standard ENV lookups
  TS_SECRET = ENV['TS_SECRET']
  #Use the standard libvirt-compatible box
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "edge-server-betzdorf-01"
  # Add this line to prevent SSH key replacement issues
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # Libvirt (KVM) Provider Settings
  config.vm.provider :libvirt do |lv|
    lv.memory = 2048
    lv.cpus = 2
    lv.machine_type = "q35" # Modern chipset for better performance
    lv.video_type = "none" # We only need CLI
  end

  # Shell Provisioning
  config.vm.provision "shell",
    env: { "TS_SECRET" => TS_SECRET },
    inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get install -y curl

    # 1. Install Tailscale
    curl -fsSL https://tailscale.com/install.sh | sh

    sudo tailscale up --reset \
                --authkey="${TS_SECRET}" \
                --hostname=edge-server-betzdorf-01 \
                --advertise-tags=tag:edge-server

    # 3. Install k3s
    curl -sfL https://get.k3s.io | sh -
    
    # 4. Metadata
    # k3s looks at the shared /vagrant folder
    sudo chmod 644 /etc/rancher/k3s/k3s.yaml
    sudo kubectl apply -f /vagrant/db-deployment.yaml
    sudo k3s kubectl apply -f /vagrant/edge-app.yaml
  SHELL
end
