{
 "title": "Retail Edge - 4 Golden Signals",
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up, kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Lag (GCP Backbone)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(retail_edge_unsynced_sales_count{kubernetes_namespace=~\"$namespace\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Traffic (Requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (rate(retail_edge_latency_seconds_count{kubernetes_namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Errors (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (increase(retail_edge_errors_total{kubernetes_namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Errors {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Latency (P95 in ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_namespace) (rate(retail_edge_latency_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[5m]))) * 1000",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Saturation (CPU Usage %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (rate(process_cpu_seconds_total{kubernetes_namespace=~\"$namespace\"}[1m])) * 100",
     "legendFormat": "CPU {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Saturation (Heap Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (go_memstats_heap_inuse_bytes{kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "Memory {{kubernetes_namespace}}"
    }
   ]
  }
 ]
}