apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-edge-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-edge
  template:
    metadata:
      labels:
        app: retail-edge
    spec:
      containers:
      - name: retail-edge-node
        image: europe-west3-docker.pkg.dev/retail-backbone-gcp/retail-repo/retail-edge-node:latest
        resources:
          requests:
            cpu: "100m"      # 10% eines CPU-Kerns (Startwert)
            memory: "128Mi"  # 128 MB RAM
          limits:
            cpu: "500m"      # Maximal 50% eines CPU-Kerns
            memory: "256Mi"  # Maximal 256 MB RAM
        ports:
        - containerPort: 8080
        # Health checks for the 4 Golden Signals
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: retail-edge-service
spec:
  type: LoadBalancer
  selector:
    app: retail-edge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080