name: Retail Edge Deployment

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: retail-backbone-gcp
  REGION: europe-west3
  REPOSITORY: retail-edge-repo
  IMAGE: retail-edge-service
  CLUSTER_NAME: retail-edge-cluster
  CLUSTER_ZONE: europe-west3-b

#permissions to allow OIDC token generation
permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  deploy:
    name: Build and Push to Artifact Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    # Authenticate with Google Cloud using OIDC
    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/962774029483/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2'
        service_account: 'github-action-sa@retail-backbone-gcp.iam.gserviceaccount.com'
        project_id: 'retail-backbone-gcp'
        token_format: 'access_token'

    # Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Docker Auth
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    # Build the Docker image and push it to Artifact Registry
    - name: Build and Push Container
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}