name: Go Quality Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Verify Build
      run: go build -v ./cmd/server/main.go

    - name: Run Vet
       # SRE-Tipp: 'go vet' prüft auf häufige Fehler, die Compiler oft übersehen
      run: go vet ./...